# The URL the site will be built for
base_url = "https://marcpinet.fr"
title = "Marc Pinet"
description = "Personal home page."
generate_feed = false
minify_html = true

output_dir = "public"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "css"
render_emoji = true

[extra]
favicon = "/favicon.svg"

menu = [
    { name = "Publications", url = "/publications", weight = 1 },
    { name = "Projects", url = "/projects", weight = 2 },
    { name = "Experience", url = "/experience", weight = 3 },
    { name = "Education", url = "/education", weight = 4 },
    { name = "Misc.", url = "/misc", weight = 5 },
]

socials = [
    { name = "Email", url = "mailto:marc.pinet.06@gmail.com" },
    { name = "Scholar", url = "https://scholar.google.com/citations?user=NsXT970AAAAJ" },
    { name = "GitHub", url = "https://github.com/marcpinet/" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/marc-pinet/" },
    { name = "X", url = "https://x.com/marcpinet0/" },
    { name = "CV", url = "https://raw.githubusercontent.com/marcpinet/marcpinet.github.io/cv/cv.pdf" },
]
